# Generated by Django 4.1.3 on 2022-11-28 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField(max_length=1000)),
                ('cast', models.CharField(max_length=255)),
                ('poster', models.URLField()),
                ('rated', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=255)),
                ('date_released', models.DateField()),
                ('roten_score', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('imdbId', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('likes', models.ManyToManyField(related_name='user_movie_likes', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(related_name='user_movue_watch_list', to=settings.AUTH_USER_MODEL)),
                ('watched', models.ManyToManyField(related_name='user_movie_watched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
