# Generated by Django 4.1.3 on 2022-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
