# Generated by Django 4.1.3 on 2022-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_cast_alter_movie_date_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.CharField(max_length=255),
        ),
    ]
